# infrastructure/kubernetes/secrets/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: eureka-credentials
  namespace: real-estate
type: Opaque
data:
  username: YWRtaW4= # base64 encoded "admin"
  password: YWRtaW4xMjM= # base64 encoded "admin123"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: real-estate
type: Opaque
data:
  secret: NTM2NzU2NkI1OTcwMzM3MzM2NzYzOTc5MkY0MjNGNDUyODQ4MkI0RDYyNTE2NTU0Njg1NzZENUE3MTM0NzQzNw== # Your encoded JWT secret
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: real-estate
type: Opaque
data:
  username: cG9zdGdyZXM= # base64 encoded "postgres"
  password: cGFzc3dvcmQxMjM= # base64 encoded "password123"
---
apiVersion: v1
kind: Secret
metadata:
  name: mail-credentials
  namespace: real-estate
type: Opaque
data:
  username: eW91ci1lbWFpbEBnbWFpbC5jb20= # base64 encoded "your-email@gmail.com"
  password: eW91ci1hcHAtcGFzc3dvcmQ= # base64 encoded "your-app-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: real-estate
type: Opaque
data:
  access-key-id: QUtJQTVJSk9YRjNZWVlVU1dURE8= # base64 encoded, replace with actual values
  secret-access-key: ZEN5eTdYbHZvRndza1JKamVjMUk3U1lyNkZHVVBWUm56MUJOQy96RA== # base64 encoded, replace with actual values
