server:
  port: 8081

spring:
  application:
    name: property-service
  datasource:
    url: jdbc:postgresql://localhost:5432/real_estate_property
    username: postgres
    password: sqluser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

eureka:
  client:
    enabled: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

aws:
  access:
    key:
      id: Your-id
  secret:
    access:
      key: your-key
  s3:
    region: ca-central-1
    bucket:
      name: real-estate-management-system

logging:
  level:
    com.realestate.property: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
