spring:
  security:
    user:
      name: ${EUREKA_USERNAME}
      password: ${EUREKA_PASSWORD}
eureka:
  server:
    enableSelfPreservation: true
    renewal-percent-threshold: 0.85
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_PEER_1:eureka-1}:8761/eureka/,http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_PEER_2:eureka-2}:8761/eureka/
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    preferIpAddress: false
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
    org.springframework.security: WARN