[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Handle redirects
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# This ensures that all routes are handled by Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

# For SPAs - redirect all routes back to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false