[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# API redirects should come first - they're more specific
[[redirects]]
  from = "/api/*"
  to = "http://34.69.232.90/api/:splat"
  status = 200
  force = true

# For client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Handle not found pages - this should be last
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404