[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle not found pages
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# For client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false