# application.yml
server:
  port: 8082

app:
  url: http://localhost:8082
  frontend-url: http://localhost:3000 # If you have a separate frontend
  email:
    from: noreply@realestate.com
    verification-url: ${app.frontend-url}/verify-email
    password-reset-url: ${app.frontend-url}/account/password/reset

spring:
  profiles:
    active: prod
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/real_estate_user
    username: postgres
    password: sqluser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: youremail@example.com
    password: yourpassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: yoursecret
  expiration: 900000 # 15 minutes in milliseconds
  refresh:
    expiration: 604800000 # 7 days in milliseconds

email:
  verification:
    expiration: 86400000 # 24 hours
  password-reset:
    expiration: 3600000 # 1 hour

eureka:
  client:
    #    enabled: false
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    preferIpAddress: false
    instance-id: ${spring.application.name}:${random.uuid}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

logging:
  level:
    root: INFO
    com.realestate.user: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
