-- Clear existing data (optional - use carefully in production)
DELETE FROM property_images;
DELETE FROM properties;

-- Insert 50 sample properties
INSERT INTO properties (id, title, description, type, status, price, bedrooms, bathrooms, area, address, city, state, zip_code, created_at, updated_at)
VALUES
(1, 'Modern Downtown Toronto Apartment', 'Beautiful modern apartment in downtown area with stunning city views', 'APARTMENT', 'AVAILABLE', 650000, 2, 2, 1200.5, '123 Yonge St', 'Toronto', 'ON', 'M5B 2H1', NOW(), NOW()),
(2, 'Luxury Yorkville Condo', 'Spacious luxury condo in prestigious Yorkville area', 'CONDO', 'AVAILABLE', 1250000, 3, 2, 1800, '100 Yorkville Ave', 'Toronto', 'ON', 'M5R 1B9', NOW(), NOW()),
(3, 'North York Family Home', 'Spacious family home with beautiful garden and modern amenities', 'HOUSE', 'AVAILABLE', 1450000, 4, 3, 2500, '45 Sheppard Ave E', 'Toronto', 'ON', 'M2N 5W9', NOW(), NOW()),
(4, 'York Mills Estate', 'Luxurious estate with premium finishes and private backyard', 'HOUSE', 'AVAILABLE', 2250000, 5, 4, 3500, '12 York Mills Rd', 'Toronto', 'ON', 'M2P 1B3', NOW(), NOW()),
(5, 'Downtown Vancouver Penthouse', 'Stunning penthouse with panoramic ocean and mountain views', 'APARTMENT', 'AVAILABLE', 1850000, 3, 2.5, 2000, '789 Pacific Blvd', 'Vancouver', 'BC', 'V6B 5E7', NOW(), NOW()),
(6, 'Waterfront Toronto Condo', 'Modern condo with lake views and resort-style amenities', 'CONDO', 'AVAILABLE', 899000, 2, 2, 1100, '15 Queens Quay E', 'Toronto', 'ON', 'M5E 0A4', NOW(), NOW()),
(7, 'Etobicoke Townhouse', 'Contemporary townhouse in family-friendly neighborhood', 'TOWNHOUSE', 'AVAILABLE', 750000, 3, 2.5, 1800, '120 The Queensway', 'Toronto', 'ON', 'M8Y 1J3', NOW(), NOW()),
(8, 'Scarborough Family Home', 'Spacious home with finished basement and large backyard', 'HOUSE', 'AVAILABLE', 950000, 4, 3, 2200, '75 Ellesmere Rd', 'Toronto', 'ON', 'M1R 4B7', NOW(), NOW()),
(9, 'Downtown Montreal Loft', 'Industrial-style loft in historic building', 'APARTMENT', 'AVAILABLE', 495000, 1, 1, 950, '215 Rue Saint-Jacques', 'Montreal', 'QC', 'H2Y 1M6', NOW(), NOW()),
(10, 'Ottawa Riverside Condo', 'Elegant condo with river views and modern finishes', 'CONDO', 'AVAILABLE', 625000, 2, 2, 1300, '150 Sussex Dr', 'Ottawa', 'ON', 'K1N 5A6', NOW(), NOW()),
(11, 'Calgary Downtown Apartment', 'Modern apartment in the heart of downtown Calgary', 'APARTMENT', 'AVAILABLE', 450000, 2, 2, 1100, '225 6 Ave SW', 'Calgary', 'AB', 'T2P 1N2', NOW(), NOW()),
(12, 'Edmonton Family Home', 'Beautiful family home with modern updates', 'HOUSE', 'AVAILABLE', 585000, 4, 3, 2400, '12224 Jasper Ave', 'Edmonton', 'AB', 'T5N 3K8', NOW(), NOW()),
(13, 'Halifax Oceanfront Condo', 'Luxury condo with Atlantic Ocean views', 'CONDO', 'AVAILABLE', 750000, 2, 2, 1400, '1475 Lower Water St', 'Halifax', 'NS', 'B3J 3Z2', NOW(), NOW()),
(14, 'Quebec City Historic Home', 'Charming home in Old Quebec with character', 'HOUSE', 'AVAILABLE', 695000, 3, 2, 1800, '25 Rue Saint-Louis', 'Quebec City', 'QC', 'G1R 3Y8', NOW(), NOW()),
(15, 'Mississauga Luxury Condo', 'High-end condo with lake views', 'CONDO', 'AVAILABLE', 825000, 2, 2, 1250, '3500 Lakeshore Rd W', 'Mississauga', 'ON', 'L5L 1B8', NOW(), NOW()),
(16, 'Kitchener Modern Townhouse', 'Contemporary townhouse in tech hub area', 'TOWNHOUSE', 'AVAILABLE', 550000, 3, 2.5, 1600, '123 Victoria St S', 'Kitchener', 'ON', 'N2G 2B4', NOW(), NOW()),
(17, 'London Ontario Family Home', 'Spacious home in family-friendly neighborhood', 'HOUSE', 'AVAILABLE', 650000, 4, 3, 2300, '1150 Richmond St', 'London', 'ON', 'N6A 3K7', NOW(), NOW()),
(18, 'Victoria Heritage House', 'Restored heritage home with modern amenities', 'HOUSE', 'AVAILABLE', 1250000, 4, 3, 2600, '45 Government St', 'Victoria', 'BC', 'V8V 2K8', NOW(), NOW()),
(19, 'Winnipeg Downtown Loft', 'Contemporary loft in Exchange District', 'APARTMENT', 'AVAILABLE', 375000, 1, 1, 850, '167 Bannatyne Ave', 'Winnipeg', 'MB', 'R3B 0R4', NOW(), NOW()),
(20, 'Regina Modern Home', 'New build with premium finishes', 'HOUSE', 'AVAILABLE', 495000, 3, 2.5, 2000, '2505 Victoria Ave', 'Regina', 'SK', 'S4P 0S4', NOW(), NOW()),
(21, 'North Vancouver Mountain View', 'Stunning home with mountain views', 'HOUSE', 'AVAILABLE', 1650000, 4, 3, 2800, '355 Mountain Hwy', 'North Vancouver', 'BC', 'V7J 2K7', NOW(), NOW()),
(22, 'Burnaby Height Luxury Condo', 'High-rise condo with city views', 'CONDO', 'AVAILABLE', 750000, 2, 2, 1100, '4808 Hazel St', 'Burnaby', 'BC', 'V5H 4T3', NOW(), NOW()),
(23, 'Richmond Garden Home', 'Beautiful home with landscaped garden', 'HOUSE', 'AVAILABLE', 1250000, 4, 3, 2400, '7373 Westminster Hwy', 'Richmond', 'BC', 'V6X 1A3', NOW(), NOW()),
(24, 'Surrey Family Estate', 'Large estate home with pool', 'HOUSE', 'AVAILABLE', 1850000, 5, 4, 3800, '13458 72 Ave', 'Surrey', 'BC', 'V3W 2N6', NOW(), NOW()),
(25, 'Oakville Lakefront Property', 'Luxury home with Lake Ontario views', 'HOUSE', 'AVAILABLE', 2450000, 4, 4.5, 3500, '175 Lakeshore Rd E', 'Oakville', 'ON', 'L6J 1H3', NOW(), NOW()),
(26, 'Burlington Waterfront Condo', 'Modern condo with lake views', 'CONDO', 'AVAILABLE', 750000, 2, 2, 1200, '2085 Lakeshore Rd', 'Burlington', 'ON', 'L7R 1A3', NOW(), NOW()),
(27, 'Hamilton Mountain Home', 'Spacious home with escarpment views', 'HOUSE', 'AVAILABLE', 650000, 3, 2.5, 2100, '525 Upper Wellington St', 'Hamilton', 'ON', 'L9A 3P5', NOW(), NOW()),
(28, 'St. Catharines Heritage Home', 'Restored century home with character', 'HOUSE', 'AVAILABLE', 595000, 4, 2, 2200, '215 King St', 'St. Catharines', 'ON', 'L2R 3J9', NOW(), NOW()),
(29, 'Oshawa Modern Build', 'New construction with latest amenities', 'HOUSE', 'AVAILABLE', 750000, 4, 3, 2400, '250 Simcoe St N', 'Oshawa', 'ON', 'L1G 4T2', NOW(), NOW()),
(30, 'Barrie Lakefront Cottage', 'Charming cottage with lake access', 'HOUSE', 'AVAILABLE', 850000, 3, 2, 1600, '125 Dunlop St E', 'Barrie', 'ON', 'L4M 1A6', NOW(), NOW()),
(31, 'Kelowna Wine Country Estate', 'Luxury estate near vineyards', 'HOUSE', 'AVAILABLE', 1950000, 5, 4, 4200, '1829 Water St', 'Kelowna', 'BC', 'V1Y 1A5', NOW(), NOW()),
(32, 'Nanaimo Oceanfront Home', 'Beautiful home with Pacific views', 'HOUSE', 'AVAILABLE', 1250000, 3, 2.5, 2300, '70 Front St', 'Nanaimo', 'BC', 'V9R 5H7', NOW(), NOW()),
(33, 'Kingston Historic Property', 'Heritage home in historic district', 'HOUSE', 'AVAILABLE', 650000, 4, 2, 2400, '125 King St E', 'Kingston', 'ON', 'K7L 2Z3', NOW(), NOW()),
(34, 'Guelph Century Home', 'Restored Victorian with modern updates', 'HOUSE', 'AVAILABLE', 750000, 4, 3, 2600, '55 Wyndham St N', 'Guelph', 'ON', 'N1H 7T8', NOW(), NOW()),
(35, 'Moncton Family Home', 'Spacious home in quiet neighborhood', 'HOUSE', 'AVAILABLE', 425000, 4, 2.5, 2200, '123 Main St', 'Moncton', 'NB', 'E1C 1B8', NOW(), NOW()),
(36, 'Saint John Harbor View', 'Historic home with water views', 'HOUSE', 'AVAILABLE', 395000, 3, 2, 1900, '223 Prince William St', 'Saint John', 'NB', 'E2L 2B7', NOW(), NOW()),
(37, 'Charlottetown Heritage Home', 'Character home in historic area', 'HOUSE', 'AVAILABLE', 450000, 3, 2, 2000, '145 Great George St', 'Charlottetown', 'PE', 'C1A 4K6', NOW(), NOW()),
(38, 'St. Johns Harbor House', 'Colorful row house with ocean views', 'HOUSE', 'AVAILABLE', 475000, 3, 2, 1800, '215 Water St', 'St. Johns', 'NL', 'A1C 1B5', NOW(), NOW()),
(39, 'Fredericton Riverside Home', 'Beautiful home along St. John River', 'HOUSE', 'AVAILABLE', 425000, 4, 2.5, 2300, '312 University Ave', 'Fredericton', 'NB', 'E3B 4H7', NOW(), NOW()),
(40, 'Saskatoon River Property', 'Modern home with river valley views', 'HOUSE', 'AVAILABLE', 585000, 4, 3, 2400, '518 Saskatchewan Cres E', 'Saskatoon', 'SK', 'S7N 0L9', NOW(), NOW()),
(41, 'White Rock Ocean View', 'Luxury home with panoramic views', 'HOUSE', 'AVAILABLE', 1850000, 4, 3.5, 3000, '15621 Marine Dr', 'White Rock', 'BC', 'V4B 1C9', NOW(), NOW()),
(42, 'Coquitlam Mountain View', 'Modern home with mountain vistas', 'HOUSE', 'AVAILABLE', 1250000, 4, 3, 2600, '1120 Pinetree Way', 'Coquitlam', 'BC', 'V3B 7S8', NOW(), NOW()),
(43, 'New Westminster Heritage', 'Restored heritage home with character', 'HOUSE', 'AVAILABLE', 950000, 3, 2.5, 2200, '215 Queens Ave', 'New Westminster', 'BC', 'V3L 1J9', NOW(), NOW()),
(44, 'Port Moody Waterfront', 'Contemporary home near inlet', 'HOUSE', 'AVAILABLE', 1150000, 4, 3, 2400, '125 Newport Dr', 'Port Moody', 'BC', 'V3H 5C3', NOW(), NOW()),
(45, 'Abbotsford Country Estate', 'Spacious estate on acreage', 'HOUSE', 'AVAILABLE', 1450000, 5, 4, 3800, '2345 McMillan Rd', 'Abbotsford', 'BC', 'V2S 7R3', NOW(), NOW()),
(46, 'Laval Luxury Home', 'Modern luxury home with high-end finishes', 'HOUSE', 'AVAILABLE', 950000, 4, 3, 2600, '1550 Boulevard Le Corbusier', 'Laval', 'QC', 'H7S 1Z2', NOW(), NOW()),
(47, 'Longueuil River View', 'Beautiful home with St. Lawrence views', 'HOUSE', 'AVAILABLE', 750000, 3, 2.5, 2200, '135 Chemin de la Rive', 'Longueuil', 'QC', 'J4H 4C3', NOW(), NOW()),
(48, 'Gatineau Park Area', 'Charming home near nature park', 'HOUSE', 'AVAILABLE', 550000, 3, 2, 1900, '245 Boulevard des Grives', 'Gatineau', 'QC', 'J9A 0C7', NOW(), NOW()),
(49, 'Sherbrooke Countryside', 'Peaceful home with mountain views', 'HOUSE', 'AVAILABLE', 475000, 3, 2, 2000, '789 Rue King Ouest', 'Sherbrooke', 'QC', 'J1H 1R8', NOW(), NOW()),
(50, 'Trois-Rivieres Historic', 'Classic home in historic district', 'HOUSE', 'AVAILABLE', 425000, 3, 2, 1800, '458 Rue des Forges', 'Trois-Rivieres', 'QC', 'G9A 2H3', NOW(), NOW());

-- Set the sequence to continue from the highest ID
SELECT setval('properties_id_seq', (SELECT MAX(id) FROM properties));

-- Insert property images (cycling through the provided URLs)
INSERT INTO property_images (id, property_id, name, type, url, is_main, display_order, file_size, created_at, updated_at)
VALUES
-- Main images for each property (cycling through the 6 provided URLs)
(1, 1, 'downtown-apartment.jpg', 'image/jpeg', '/images/properties/downtown-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(2, 2, 'new-york-apartment.jpg', 'image/jpeg', '/images/properties/new-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(3, 3, 'toronto-apartment.jpg', 'image/jpeg', '/images/properties/toronto-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(4, 4, 'york-mills-apartment.jpg', 'image/jpeg', '/images/properties/york-mills-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(5, 5, 'yorkville-apartment.jpg', 'image/jpeg', '/images/properties/yorkville-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(6, 6, 'north-york-apartment.jpg', 'image/jpeg', '/images/properties/north-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(7, 7, 'downtown-apartment.jpg', 'image/jpeg', '/images/properties/downtown-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(8, 8, 'new-york-apartment.jpg', 'image/jpeg', '/images/properties/new-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(9, 9, 'toronto-apartment.jpg', 'image/jpeg', '/images/properties/toronto-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(10, 10, 'york-mills-apartment.jpg', 'image/jpeg', '/images/properties/york-mills-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(11, 11, 'yorkville-apartment.jpg', 'image/jpeg', '/images/properties/yorkville-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(12, 12, 'north-york-apartment.jpg', 'image/jpeg', '/images/properties/north-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(13, 13, 'downtown-apartment.jpg', 'image/jpeg', '/images/properties/downtown-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(14, 14, 'new-york-apartment.jpg', 'image/jpeg', '/images/properties/new-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(15, 15, 'toronto-apartment.jpg', 'image/jpeg', '/images/properties/toronto-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(16, 16, 'york-mills-apartment.jpg', 'image/jpeg', '/images/properties/york-mills-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(17, 17, 'yorkville-apartment.jpg', 'image/jpeg', '/images/properties/yorkville-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(18, 18, 'north-york-apartment.jpg', 'image/jpeg', '/images/properties/north-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(19, 19, 'downtown-apartment.jpg', 'image/jpeg', '/images/properties/downtown-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(20, 20, 'new-york-apartment.jpg', 'image/jpeg', '/images/properties/new-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(21, 21, 'toronto-apartment.jpg', 'image/jpeg', '/images/properties/toronto-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(22, 22, 'york-mills-apartment.jpg', 'image/jpeg', '/images/properties/york-mills-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(23, 23, 'yorkville-apartment.jpg', 'image/jpeg', '/images/properties/yorkville-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(24, 24, 'north-york-apartment.jpg', 'image/jpeg', '/images/properties/north-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(25, 25, 'downtown-apartment.jpg', 'image/jpeg', '/images/properties/downtown-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(26, 26, 'new-york-apartment.jpg', 'image/jpeg', '/images/properties/new-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(27, 27, 'toronto-apartment.jpg', 'image/jpeg', '/images/properties/toronto-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(28, 28, 'york-mills-apartment.jpg', 'image/jpeg', '/images/properties/york-mills-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(29, 29, 'yorkville-apartment.jpg', 'image/jpeg', '/images/properties/yorkville-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(30, 30, 'north-york-apartment.jpg', 'image/jpeg', '/images/properties/north-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(31, 31, 'downtown-apartment.jpg', 'image/jpeg', '/images/properties/downtown-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(32, 32, 'new-york-apartment.jpg', 'image/jpeg', '/images/properties/new-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(33, 33, 'toronto-apartment.jpg', 'image/jpeg', '/images/properties/toronto-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(34, 34, 'york-mills-apartment.jpg', 'image/jpeg', '/images/properties/york-mills-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(35, 35, 'yorkville-apartment.jpg', 'image/jpeg', '/images/properties/yorkville-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(36, 36, 'north-york-apartment.jpg', 'image/jpeg', '/images/properties/north-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(37, 37, 'downtown-apartment.jpg', 'image/jpeg', '/images/properties/downtown-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(38, 38, 'new-york-apartment.jpg', 'image/jpeg', '/images/properties/new-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(39, 39, 'toronto-apartment.jpg', 'image/jpeg', '/images/properties/toronto-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(40, 40, 'york-mills-apartment.jpg', 'image/jpeg', '/images/properties/york-mills-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(41, 41, 'yorkville-apartment.jpg', 'image/jpeg', '/images/properties/yorkville-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(42, 42, 'north-york-apartment.jpg', 'image/jpeg', '/images/properties/north-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(43, 43, 'downtown-apartment.jpg', 'image/jpeg', '/images/properties/downtown-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(44, 44, 'new-york-apartment.jpg', 'image/jpeg', '/images/properties/new-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(45, 45, 'toronto-apartment.jpg', 'image/jpeg', '/images/properties/toronto-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(46, 46, 'york-mills-apartment.jpg', 'image/jpeg', '/images/properties/york-mills-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(47, 47, 'yorkville-apartment.jpg', 'image/jpeg', '/images/properties/yorkville-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(48, 48, 'north-york-apartment.jpg', 'image/jpeg', '/images/properties/north-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(49, 49, 'downtown-apartment.jpg', 'image/jpeg', '/images/properties/downtown-apartment.jpg', true, 0, NULL, NOW(), NOW()),
(50, 50, 'new-york-apartment.jpg', 'image/jpeg', '/images/properties/new-york-apartment.jpg', true, 0, NULL, NOW(), NOW()),

-- Add secondary images for some properties
(51, 1, 'toronto-apartment.jpg', 'image/jpeg', '/images/properties/toronto-apartment.jpg', false, 1, NULL, NOW(), NOW()),
(52, 1, 'yorkville-apartment.jpg', 'image/jpeg', '/images/properties/yorkville-apartment.jpg', false, 2, NULL, NOW(), NOW()),
(53, 2, 'downtown-apartment.jpg', 'image/jpeg', '/images/properties/downtown-apartment.jpg', false, 1, NULL, NOW(), NOW()),
(54, 2, 'york-mills-apartment.jpg', 'image/jpeg', '/images/properties/york-mills-apartment.jpg', false, 2, NULL, NOW(), NOW()),
(55, 3, 'north-york-apartment.jpg', 'image/jpeg', '/images/properties/north-york-apartment.jpg', false, 1, NULL, NOW(), NOW()),
(56, 4, 'toronto-apartment.jpg', 'image/jpeg', '/images/properties/toronto-apartment.jpg', false, 1, NULL, NOW(), NOW()),
(57, 5, 'downtown-apartment.jpg', 'image/jpeg', '/images/properties/downtown-apartment.jpg', false, 1, NULL, NOW(), NOW()),
(58, 10, 'yorkville-apartment.jpg', 'image/jpeg', '/images/properties/yorkville-apartment.jpg', false, 1, NULL, NOW(), NOW()),
(59, 15, 'york-mills-apartment.jpg', 'image/jpeg', '/images/properties/york-mills-apartment.jpg', false, 1, NULL, NOW(), NOW()),
(60, 20, 'north-york-apartment.jpg', 'image/jpeg', '/images/properties/north-york-apartment.jpg', false, 1, NULL, NOW(), NOW());

-- Set the sequence to continue from the highest ID
SELECT setval('property_images_id_seq', (SELECT MAX(id) FROM property_images));