# infrastructure/kubernetes/deployments/property-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-service
  namespace: real-estate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: property-service
  template:
    metadata:
      labels:
        app: property-service
    spec:
      containers:
        - name: property-service
          image: ${YOUR_DOCKER_REGISTRY}/property-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              value: real_estate_property
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: EUREKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: eureka-credentials
                  key: username
            - name: EUREKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eureka-credentials
                  key: password
            - name: EUREKA_HOST
              value: service-registry-lb
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-access-key
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: aws-config
                  key: region
            - name: AWS_S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: aws-config
                  key: bucket-name
          resources:
            requests:
              memory: '512Mi'
              cpu: '250m'
            limits:
              memory: '1Gi'
              cpu: '500m'
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: property-service
  namespace: real-estate
spec:
  selector:
    app: property-service
  ports:
    - port: 80
      targetPort: 8081
  type: ClusterIP
