# infrastructure/kubernetes/deployments/user-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: real-estate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ${YOUR_DOCKER_REGISTRY}/user-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              value: real_estate_user
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: EUREKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: eureka-credentials
                  key: username
            - name: EUREKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eureka-credentials
                  key: password
            - name: EUREKA_HOST
              value: service-registry-lb
            - name: APP_URL
              value: 'http://api.your-production-domain.com/api'
            - name: FRONTEND_URL
              value: 'https://your-production-domain.com'
            - name: MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mail-config
                  key: host
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mail-config
                  key: port
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mail-credentials
                  key: username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-credentials
                  key: password
          resources:
            requests:
              memory: '512Mi'
              cpu: '250m'
            limits:
              memory: '1Gi'
              cpu: '500m'
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 90
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: real-estate
spec:
  selector:
    app: user-service
  ports:
    - port: 80
      targetPort: 8082
  type: ClusterIP
