version: '3.8'

services:
  eureka-node1:
    build: .
    hostname: eureka-node1
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=ha
      - EUREKA_NODE_ID=node1
      - EUREKA_INSTANCE_HOSTNAME=eureka-node1
      - EUREKA_USERNAME=admin
      - EUREKA_PASSWORD=secure_password
      - EUREKA_ZONE=zone1
      - EUREKA_PEER_URLS=http://admin:secure_password@eureka-node2:8761/eureka/,http://admin:secure_password@eureka-node3:8761/eureka/
    volumes:
      - eureka_logs_1:/var/log/eureka
    networks:
      - eureka-net

  eureka-node2:
    build: .
    hostname: eureka-node2
    ports:
      - "8762:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=ha
      - EUREKA_NODE_ID=node2
      - EUREKA_INSTANCE_HOSTNAME=eureka-node2
      - EUREKA_USERNAME=admin
      - EUREKA_PASSWORD=secure_password
      - EUREKA_ZONE=zone1
      - EUREKA_PEER_URLS=http://admin:secure_password@eureka-node1:8761/eureka/,http://admin:secure_password@eureka-node3:8761/eureka/
    volumes:
      - eureka_logs_2:/var/log/eureka
    networks:
      - eureka-net

  eureka-node3:
    build: .
    hostname: eureka-node3
    ports:
      - "8763:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=ha
      - EUREKA_NODE_ID=node3
      - EUREKA_INSTANCE_HOSTNAME=eureka-node3
      - EUREKA_USERNAME=admin
      - EUREKA_PASSWORD=secure_password
      - EUREKA_ZONE=zone1
      - EUREKA_PEER_URLS=http://admin:secure_password@eureka-node1:8761/eureka/,http://admin:secure_password@eureka-node2:8761/eureka/
    volumes:
      - eureka_logs_3:/var/log/eureka
    networks:
      - eureka-net

networks:
  eureka-net:
    driver: bridge

volumes:
  eureka_logs_1:
  eureka_logs_2:
  eureka_logs_3: