server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/real_estate_analytics
    username: postgres
    password: sqluser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    #    enabled: false
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    preferIpAddress: false
    instance-id: ${spring.application.name}:${random.uuid}
