spring:
  application:
    name: analytics-service
  profiles:
    active: prod


#Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    filter: true
  packages-to-scan: com.realestate.analytics.controller
  paths-to-match: /api/**

logging:
  level:
    root: INFO
    com.realestate.analytics: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE