spring:
  application:
    name: analytics-service
  profiles:
    active: prod
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=30m

services:
  property:
    url: http://localhost:8081


#Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    filter: true
    tryItOutEnabled: true
  packages-to-scan: com.realestate.analytics
  paths-to-match: /api/**

logging:
  level:
    root: INFO
    com.realestate.analytics: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE